version: "3.8"
services:
  mysqldb:
    container_name: database
    image: mysql:8
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=superPassword
      - MYSQL_DATABASE=codeseek_football_management
    ports:
      - "3307:3306"
    volumes:
      - ./src/main/resources/initDb.sql:/docker-entrypoint-initdb.d/initDb.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 7s
      start_period: 6s
      retries: 10
    networks:
      - common-network
  app:
    container_name: app
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - common-network
networks:
  common-network:
    driver: bridge